# Use Python 3.10-slim as the base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all files into the working directory
COPY . .

# Update pip and install dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Expose the Flask application's port
EXPOSE 5000

# Command to run the Flask application
CMD ["python", "app.py"]
